### ISSUE TITLE
Run the tryondiffusion Code

### ISSUE THREAD

**Issue by syedhaideralizaidi** [tryonlabs/tryondiffusion#55]
Is this project available for use or is it under construction? Plus if it is available kindly guide how to run this since there is only setup file to download dependencies only.

**Comment by kailashahirwar** [comment]
It is under construction for now. Feel free to make improvements to the code and create a pull request.

**Comment by jaeyo03** [comment]
Oh... So there is no way to test it at all..?

**Comment by tanayag** [comment]
We'll release another iteration, facing some issues with resources as of now. If you want to test forward pass and backward pass for the network, you can do so on colab's pro version, just do so on TPU, because it will not load even on vRAM of 40GB A100 GPU.

There is a small bug in cross attention. We'll push the fix to that bug, documentation, when we release the weights in future.
